"""
Filesystem path containment helper.

Every path stored in the database in this app is generated by our own
server-side code (UUID-based filenames under AUDIO_SAMPLE_DIR /
GENERATED_DIR) -- never taken directly from user input. We still verify
containment before any read/delete/serve operation as defense in depth,
and to keep static-analysis path-traversal checks (CWE-23) meaningfully
satisfied rather than suppressed.
"""
from pathlib import Path
from typing import List


class UnsafePathError(ValueError):
    """Raised when a stored path resolves outside its expected storage root."""


def ensure_within(path_str: str, allowed_dirs: List[Path]) -> Path:
    resolved = Path(path_str).resolve()
    for allowed in allowed_dirs:
        allowed_resolved = allowed.resolve()
        if resolved == allowed_resolved or allowed_resolved in resolved.parents:
            return resolved
    raise UnsafePathError(f"Path '{path_str}' is outside allowed storage directories.")
